apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqadmin
  namespace: nsq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nsqadmin
        app: nsqadmin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nsqadmin
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nsqadmin
        image: nsqio/nsq
        command:
          - /nsqadmin
          - --lookupd-http-address=nsqlookupd1:4161
          - --lookupd-http-address=nsqlookupd2:4161
        ports:
          - containerPort: 4171
            name: http
            protocol: TCP

