apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqlookupd1
  namespace: nsq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nsqlookupd1
    spec:
      containers:
      - name: nsqlookup1
        image: nsqio/nsq
        command:
          - /nsqlookupd
        ports:
          - containerPort: 4160
            name: tcp
            protocol: TCP
          - containerPort: 4161
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd1
  namespace: nsq
  labels:
    name: nsqlookupd1
spec:
  ports:
    - port: 4160
      name: tcp
      targetPort: 4160
    - port: 4161
      name: http
      targetPort: 4161
  selector:
    name: nsqlookupd1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqlookupd2
  namespace: nsq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nsqlookupd2
    spec:
      containers:
      - name: nsqlookup2
        image: nsqio/nsq
        command:
          - /nsqlookupd
        ports:
          - containerPort: 4160
            name: tcp
            protocol: TCP
          - containerPort: 4161
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd2
  namespace: nsq
  labels:
    name: nsqlookupd2
spec:
  ports:
    - port: 4160
      name:
      targetPort: 4160
    - port: 4161
      name: http
      targetPort: 4161
  selector:
    name: nsqlookupd2
