apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: evedata
  namespace: default
spec:
  domains:
  - evedata.org
  - www.evedata.org
  - mail.evedata.org
  - grafana.evedata.org
  - graylog.evedata.org
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: cloudflare
      credentialSecretName: voyager-cloudflare
  storage:
    secret:
      name: cert-evedata
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: vanguard-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/use-host-port: "true"
    ingress.appscode.com/replicas: '2'
spec:
  tls:
    - secretName: cert-evedata
      hosts:
      - evedata.org
      - www.evedata.org
      - mail.evedata.org
  nodeSelector:
    loadbalancer: voyager
  rules:
  - host: www.evedata.org
    tcp:
      port: 443
      backend:
        serviceName: vanguard.evedata
        servicePort: '3000'
  - host: mail.evedata.org
    tcp:
      port: 993
      backend:
        serviceName: mailserver.evedata
        servicePort: '993'
  - host: mail.evedata.org
    tcp:
      port: 465
      backend:
        serviceName: mailserver.evedata
        servicePort: '465'
  - host: www.evedata.org
    tcp:
      port: 8080
      backend:
        serviceName: grafana.monitoring
        servicePort: '3000'