apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-artifice
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-artifice
      labels:
        app: artifice
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - artifice
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-artifice
        image: antihax/evedata-artifice
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        - name: ESI_SECRET
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: secret
        - name: ESI_CLIENTID
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: clientID
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        - name: ESI_REFRESHKEY
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: refreshKey
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
