apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-discordbottemp
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-discordbottemp
      labels:
        app: discordbottemp
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - discordbottemp
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-discordbottemp
        image: antihax/evedata-discordbottemp
        imagePullPolicy: Always
        env:
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-secret
              key: discord-token
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
