apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: evedata
spec:
  ports:
  - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sql
  namespace: evedata
subsets:
- addresses:
  - ip: 192.168.10.3
  ports:
  - port: 3306
