apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-hammer
  namespace: evedata
spec:
  replicas: 3
  template:
    metadata:
      name: evedata-hammer
      labels:
        app: hammer
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hammer
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-hammer
        image: antihax/evedata-hammer
        imagePullPolicy: Always
        env:
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        - name: ESI_REFRESHKEY
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: refreshKey
        - name: ESI_SECRET_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: secret-tokenstore
        - name: ESI_CLIENTID_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: clientID-tokenstore
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
