apiVersion: v1
kind: Namespace
metadata:
  name: evedata
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-marketcollector
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-marketcollector
      labels:
        app: marketcollector
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - marketcollector
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-marketcollector
        image: antihax/evedata-marketcollector
        imagePullPolicy: Always
        env:
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
