apiVersion: v1
kind: Namespace
metadata:
  name: evedata
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-marketwatch
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-marketwatch
      labels:
        app: marketwatch
        esi-connector: true
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - marketwatch
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-marketwatch
        image: antihax/eve-marketwatch
        imagePullPolicy: Always
        env:
        - name: ESI_SECRET_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: secret-tokenstore
        - name: ESI_CLIENTID_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: clientID-tokenstore
        - name: ESI_REFRESHKEY
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: refreshKey
        ports:
        - containerPort: 3000
        - containerPort: 3005
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: marketwatch
  namespace: evedata
spec:
  selector:
    app: marketwatch
  ports:
  - name: marketwatch
    protocol: TCP
    port: 3005
    targetPort: 3005
