apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-nail
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-nail
      labels:
        app: nail
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nail
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-nail
        image: antihax/evedata-nail
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
