apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-nail
  namespace: evedata
spec:
  replicas: 3
  template:
    metadata:
      name: evedata-nail
      labels:
        app: evedata
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: evedata-nail
        image: antihax/evedata-nail
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
