apiVersion: v1
kind: Namespace
metadata:
  name: evedata
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: evedata
type: Opaque
data:
  password: BASE64PASSWORD=
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-password
  namespace: evedata
type: Opaque
data:
  sqlauth: BASE64PASSWORD=
---
apiVersion: v1
kind: Secret
metadata:
  name: esi-secret
  namespace: evedata
type: Opaque
data:
  refreshKey: BASE64REFRESHKEY=
  refreshCharID: BASE64REFRESHCHARID=
  secret-sso: BASE64SECRET=
  clientID-sso: BASE64CLIENTID=
  secret-tokenserver: BASE64SECRET=
  clientID-tokenserver: BASE64CLIENTID=
  secret-discord: BASE64SECRET=
  clientID-discord: BASE64CLIENTID=
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-secret
  namespace: evedata
type: Opaque
data:
  discord-token: BASE64TOKEN=