
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-zkillboard
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-zkillboard
      labels:
        app: zkillboard
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zkillboard
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-zkillboard
        image: antihax/evedata-zkillboard
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
